name: Guns
version: '${project.version}'
main: com.ren.guns.Main
api-version: 1.18
authors: [ ren ]
description: This is a Test Plugin
website: github.com/ren-ben
commands:
  w:
    description: "Used to weaponize certain Tools like le Hoe"